### ISSUE TITLE
老哥，请问这个baseline可以排第几呢

### ISSUE THREAD

**Issue by tanklandry** [apple55bc/CCF-BDCI-qianyan#2]

**Comment by apple55bc** [comment]
https://www.datafountain.cn/competitions/470/datasets
2020的B榜第2，决赛第1
2021的任务稍有不同，没跑。

**Comment by tanklandry** [comment]
厉害了！请问数据预处理的入口方法是哪一个呢

**Comment by apple55bc** [comment]
知识对话不需要预处理，闲聊在code/recall/model_recall.py 推荐对话直接看https://github.com/apple55bc/bd-chat-2020吧 运行 bd-chat-2020/code/data_deal/pre_trans.py
