### ISSUE TITLE
知识对话要训多久呢？训到后面全是重复的词

### ISSUE THREAD

**Issue by shaoqb** [apple55bc/CCF-BDCI-qianyan#3]
![image](https://user-images.githubusercontent.com/31532434/115178133-3d477880-a103-11eb-9343-ae076ecf4a7d.png)

**Comment by apple55bc** [comment]
你训练多久了。如果没改代码应该没问题，3w epoch不需要训练完。只记得之前好像训练了不超过10个小时 3090。
最近我会再跑一次这个代码。

**Comment by shaoqb** [comment]
训练十几个小时吧。前面看着效果还行，后面就全是重复的词了。ps: 可以加一下联系方式么？

**Comment by apple55bc** [comment]
> 训练十几个小时吧。前面看着效果还行，后面就全是重复的词了。ps: 可以加一下联系方式么？

QQ  1131583188
